[package]
name = "makerpnp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive", "env"], optional = true }
anyhow = { version = "1.0.86" }
csv = { version = "1.3.0" }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = { version = "1.0.61" }
termtree = { version = "0.4.1", optional = true }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
predicates-tree = { version = "1.0.9" }
heck = {  version = "0.5.0" }

[dev-dependencies]
predicates = {  version = "3.1.0" }
assert_cmd = { version = "2.0.14" }
tempfile = { version = "3.10.1" }
indoc = { version = "2.0.5" }
csv = { version = "1.3.0" }
serde = { version = "1.0.203", features = ["derive"] }
assert_fs = { version = "1.1.1" }

[features]
cli = [
    "dep:clap",
    "dep:termtree",
]

[[bin]]
name = "variantbuilder"
test = true
bench = false
required-features = ["cli"]

