[workspace]
# Due to the requirement for test dependencies, binaries we need to use the resolver otherwise
# the "testing" feature gets pulled in when you don't want it to.
# See https://github.com/rust-lang/cargo/issues/4866
# See https://doc.rust-lang.org/beta/cargo/reference/resolver.html#resolver-versions
resolver = "2"

members = [
    "crates/cli",
    "crates/pnp",
    "crates/cli",
    "crates/i18n",
    "crates/planning",
    "crates/stores",
    "crates/part_mapper",
    "crates/assembly",
    "crates/eda",
    "crates/util",
    "crates/criteria",
    "crates/planner_app",
    "crates/planner_cli",
    "crates/makerpnp_reactive",
    "crates/planner_gui_cushy",
    "crates/planner_gui_egui",
    "crates/variantbuilder_app",
    "crates/variantbuilder_cli",
]

[workspace.dependencies]
thiserror = { version = "2.0.7" }
anyhow = { version = "1.0.86" }
regex = { version = "1.10.6" }
time = { version = "0.3.36" }
indexmap = { version = "2.4.0" }
slotmap = { version = "1.0.7" }
heck = { version = "0.5.0" }
futures = "0.3.31"
async-std = "1.13.0"
petgraph = { version = "0.6.5"}
csv = { version = "1.3.0" }
base64 = { version = "0.22.1"}
termtree = { version = "0.5.1"}
rust_decimal = { version = "1.35.0"}
rust_decimal_macros = { version = "1.35"}
derivative = { version = "2.2.0" }

# cli
clap = { version = "4.5.8" }
clap-verbosity-flag = { version = "3.0.2" }
argfile = { version = "0.2.1" }

# logging
tracing = { version = "0.1.40"}
tracing-subscriber = { version = "0.3.18" }
# only for `as_trace`
tracing-log = { version = "0.2.0" }

# serialization
serde = { version = "1.0.203" }
serde_json = { version = "1.0.127" }
serde_with = { version = "3.9.0" }
serde_regex = { version = "1.1.0" }

# crux app
crux_core = { version = "0.12.0" }

# gui (cushy)
cushy = { git = "https://github.com/makerpnp/cushy.git", tag = "20250205-2314", default-features = false }

# gui (egui)
egui = { version = "0.31.1", features = ["serde"]}
egui_extras = { version = "0.31.1", default-features = false }
eframe = { version = "0.31.1", default-features = false }
egui_taffy = "0.7.0"
egui-i18n = { git = "https://github.com/fewensa/egui-i18n", rev = "3be4d89e6328d545a715529ac80415f49d675756", features = ["fluent"] }
egui_mobius = "0.3.0-alpha.17"
egui_mobius_reactive = "0.3.0-alpha.17"
egui_material_icons = { git = "https://github.com/lucasmerlin/hello_egui.git", tag = "hello_egui-v0.8.0" }
egui_ltreeview = { version = "0.1.10" }

rfd = "0.15.2"

# validation
validator = { version = "0.20.0", features = ["derive"] }

# i18n
unic-langid = "0.9.5"
fluent = "0.16"
fluent-bundle = "0.15.3"

# testing
rstest = { version = "0.23.0" }
assert_cmd = { version = "2.0.14" }
assert_fs = { version = "1.1.1" }
tempfile = { version = "3.10.1" }
indoc = { version = "2.0.5" }
predicates = { version = "3.1.0" }
predicates-tree = { version = "1.0.11" }

# tasks/async
tokio = { version = "1.43.0", features = ["full"]}
crossbeam-channel = { version = "0.5.13" }
