[package]
name = "makerpnp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive", "env"], optional = true }
anyhow = { version = "1.0.86", optional = true }

[dev-dependencies]
predicates = {  version = "3.1.0" }
assert_cmd = { version = "2.0.14" }

[features]
cli = [
    "dep:clap",
    "dep:anyhow",
]

[[bin]]
name = "variantbuilder"
bench = false
required-features = ["cli"]

