[workspace]
# Due to the requirement for test dependencies, binaries we need to use the resolver otherwise
# the "testing" feature gets pulled in when you don't want it to.
# See https://github.com/rust-lang/cargo/issues/4866
# See https://doc.rust-lang.org/beta/cargo/reference/resolver.html#resolver-versions
resolver = "2"

members = [
    "common/args",
    "common/cli",
    "common/criteria",
    "common/cli",
    "common/i18n",
    "common/math",
    "common/util",
    "eda/eda",
    "eda/eda_units",
    "gerber/gerber",
    "gerber/gerber_viewer_egui",
    "pnp/pnp",
    "planning/assembly",
    "planning/part_mapper",
    "planning/package_mapper",
    "planning/planner_app",
    "planning/planner_cli",
    "planning/planner_gui_egui",
    "planning/planning",
    "planning/stores",
    "planning/variantbuilder_app",
    "planning/variantbuilder_cli",
]

[workspace.dependencies]
thiserror = { version = "2.0.17" }
anyhow = { version = "1.0.100" }
regex = { version = "1.12.2" }
time = { version = "0.3.44" }
indexmap = { version = "2.12.1" }
slotmap = { version = "1.1.1" }
heck = { version = "0.5.0" }
petgraph = { version = "0.8.3"}
csv = { version = "1.4.0" }
termtree = { version = "0.5.1"}
derivative = { version = "2.2.0" }
lexical-sort = { version = "0.3.1"}
tap = { version = "1.0.1" }
uuid = { version = "1.19.0" }

# enums
strum = { version = "0.27.2" }
strum_macros = { version = "0.27.2" }

# time
# Note: using `chrono`, because it has 13k dependents vs `time`'s 3k dependents (as of 2025/04/04) 
chrono = { version = "0.4.42"}

# cli
clap = { version = "4.5.53" }
clap-verbosity-flag = { version = "3.0.4" }
argfile = { version = "0.2.1" }

# logging
log = { version = "0.4.29" }
env_logger = { version = "0.11.8" }

# tracing
tracing = { version = "0.1.44"}
tracing-subscriber = { version = "0.3.22" }
# only for `as_trace`
tracing-log = { version = "0.2.0" }

# iteration
itertools = { version = "0.14.0" }

# serialization
serde = { version = "1.0.228" }
serde_json = { version = "1.0.145" }
serde_with = { version = "3.16.1" }
serde_regex = { version = "1.1.0" }
json2markdown = { version = "0.2.1" }
typetag = { version = "0.2.21" }
dyn-eq = { version = "0.1.3" }
dyn-clone = {  version = "1.0.20" }
as-any = { version = "0.3.2" }

# crux app
crux_core = { version = "0.15.0" }

# gui (egui)
egui = { version = "0.35.0", features = ["serde"]}
epaint = { version = "0.35.0"}
egui_extras = { version = "0.35.0", default-features = false }
eframe = { version = "0.35.0", default-features = false }

egui_taffy = "0.13.0"
#egui_taffy = { git = "https://github.com/makerpnp/egui_taffy", rev = "c14e390c1f3cd6487968c5845ea205a38c6afbe2" }

egui_mobius = "0.5.0"
#egui_mobius = { git = "https://github.com/makerpnp/egui_mobius", rev = "e62f97bfcf97a831bd67dd75ab5eab9585922765" }
#egui_mobius = { path = "../../../libraries/rust/egui/egui_mobius/crates/egui_mobius" }

egui_material_icons = { git = "https://github.com/lucasmerlin/hello_egui.git", tag = "hello_egui-v0.12.0" }

egui_ltreeview = { version = "0.8.0" }
# requires a version with these PRs:
# 1 - https://github.com/LennysLounge/egui_ltreeview/pull/23
#egui_ltreeview = { git = "https://github.com/makerpnp/egui_ltreeview", rev = "6e44b06e6ab3b22d3c0f3d790be77650ae74cb53" }

egui_deferred_table = { version = "0.3.0" }
#egui_deferred_table = { git = "https://github.com/makerpnp/egui_deferred_table", rev = "67f44aaabcc9850c3f0ba2c88d54a468d2a20c5f" }
#egui_deferred_table = { path = "../../../libraries/rust/egui/egui_deferred_table" }

egui_double_slider = { version = "3.0.0"}
#egui_double_slider = { git = "https://github.com/hacknus/egui_double_slider", rev = "86df8ecd38d82198f042111ce58792e3fab546fe" }

egui_vertical_stack = { version = "0.4.0" }
#egui_vertical_stack = { path = "../egui/egui_vertical_stack" }

#egui_tool_windows = { path = "../egui/egui_tool_windows" }
egui_tool_windows = { version = "0.5.0"}

egui_dock = { version = "0.20.1" }

rfd = { version = "0.17.2" }

# images
image = { version = "0.25.9" }

# validation
validator = { version = "0.20.0", features = ["derive"] }

# i18n
#egui-i18n = { git = "https://github.com/fewensa/egui-i18n", rev = "3be4d89e6328d545a715529ac80415f49d675756", features = ["fluent"] }
#egui-i18n = { git = "https://github.com/makerpnp/egui-i18n", rev = "087c62591d8027b51641bf4bcf556106d17ea799", features = ["fluent"] }
egui-i18n = { version = "0.2.0", features = ["fluent"] }

# testing
rstest = { version = "0.26.1" }
assert_cmd = { version = "2.1.1" }
assert_fs = { version = "1.1.3" }
tempfile = { version = "3.23.0" }
indoc = { version = "2.0.7" }
predicates = { version = "3.1.3" }
predicates-tree = { version = "1.0.12" }

# profiling
profiling = { version = "1.0.17" }
puffin_http = { version = "0.16.1" }

# tasks/async
tokio = { version = "1.48.0", features = ["full"]}
crossbeam-channel = { version = "0.5.15" }
futures = {  version = "0.3.31" }
async-std = {  version = "1.13.2" }

# Gerber rendering, types and parser
# Note, these three crates are tightly coupled, ensure that only one of each appears in the dependency tree.
gerber_viewer = { version = "0.7.0"}
#gerber_viewer = { git = "https://github.com/makerpnp/gerber_viewer.git", rev = "e4ed3bd48a428f422708021ca803ce1b65d3528d" }
#gerber_viewer = { path = "../gerber-viewer" }
gerber-types = { version = "0.7.0"}
#gerber-types = { git = "https://github.com/makerpnp/gerber-types.git", rev = "357215682b77093c3693efa4fe9d74076c1685fa"}
#gerber-types = { path = "../gerber-types" }
gerber_parser = { version = "0.5.0"}
#gerber_parser = { git = "https://github.com/makerpnp/gerber-parser.git", rev = "abcd8bcef8eb4d40d1ebf53d33bbb13d8c30825f"}
#gerber_parser = { path = "../gerber-parser" }

# math
num-rational = "0.4.2"
num-traits = "0.2.19"
rust_decimal = { version = "1.39.0"}
rust_decimal_macros = { version = "1.39.0"}
# need to use the same nalgebra as used by the gerber crates.
nalgebra = { version = "0.34.1", default-features = false }


[patch.crates-io]
# fork of egui 0.32.0 with the following fixes:
# https://github.com/emilk/egui/pull/7047 - Allow resize on one both or no axis
egui = { git = "https://github.com/MakerPnP/egui.git", rev = "312bb8ec1018875fa4f7624e2e1781cdf42799aa"}
# and since epaint and other crates come from the same repo, we have to patch them too if they are used as dependencies
epaint = { git = "https://github.com/MakerPnP/egui.git", rev = "312bb8ec1018875fa4f7624e2e1781cdf42799aa"}
